### ISSUE TITLE
Modal functionality

### ISSUE THREAD

**Issue by Zeeroh0** [misterfoxy/project-1#20]
At a minimum, have the modal pop up on load of the page.
- Welcome user to PinPoint
- Brief instructions to 1. select a data set 2. click PinPoint! button 

In the future, would be dope fresh if we could have this also pop up upon the map be rendered to explain what happened ("Awesome, your data has been displayed on the map.  Click the markers to see more info. (If there are Time Buttons) Click the Time Buttons to the left to see data over time.")

Even more dope freshness would be creating some kind of browser storage so these modals only pop up through one cycle.

**Comment by misterfoxy** [comment]
added basic onload functionality to the modal. method call is immediately after document.ready
