### ISSUE TITLE
Time Button functionalities

### ISSUE THREAD

**Issue by Zeeroh0** [misterfoxy/project-1#21]
Create js for Time Buttons to change which data is being displayed in the infoWindows

**Comment by misterfoxy** [comment]
I'll take a crack at this too

**Comment by misterfoxy** [comment]
I wrote a new function called grabYear that sorts through the post-ajax data array we store on the browser side, and updates the map with a new marker with relevant data for each year. It would be nice to incorporate a way to keep the marker open as the data changes so the map doesn't have to reload, but that can be another issue to present for _Future Development_
