### ISSUE TITLE
Show "Current Year" in the map

### ISSUE THREAD

**Issue by Zeeroh0** [misterfoxy/project-1#29]
Suggested by my Mrs., maybe we can style a div w a higher z-index to render on top of the map that shows what yr the user is seeing data for.

**Comment by misterfoxy** [comment]
I agree, this would be nice. It could be cool to have the dataset name appear alongside it too.

**Comment by misterfoxy** [comment]
Updated this for the presentation so it gives relative information about the currently mapped dataset
