### ISSUE TITLE
Create logic for paramenter selection

### ISSUE THREAD

**Issue by misterfoxy** [misterfoxy/project-1#8]
We need to create logic for the parameters, including disabling certain list items or forms for the specific data-set.

**Comment by Zeeroh0** [comment]
I was thinking that we could have the parameter options be dynamically populated (to some degree) by the object's contents after the user selects what data set they want.  Just throwing an idea out there.  It'll be tricky given that we're going to be working with different structured objects in each data set

**Comment by Zeeroh0** [comment]
Took care of this by simplifying the side bar/data selection.  Parameters are now pretty much implemented after data is displayed by adding time buttons to the left.  We automized the initial scale/location of the map upon click of the PinPoint button.
